### ISSUE TITLE
multiple tags as string

### ISSUE THREAD

**Issue by SwissalpS** [mt-mods/pipeworks#116]
I'm a bit fuzzy on the discussion going into the tag support. Reading the code at:

https://github.com/mt-mods/pipeworks/blob/6c66a2f43ce4430955df4233400c3e21dd8f07b8/filter-injector.lua#L207

I would have expected the string to be passed as is to sanitize function so user can send a string with multiple tags.

I probably missed the part of the discussion where this was voted against for whatever reason. Just checking here.

**Comment by OgelGames** [comment]
It wasn't really discussed, but since it's `msg.tag` (singular), then it makes sense to only accept one tag. However, by that logic you should be able to send a string with multiple tags using `msg.tags`.

**Comment by SwissalpS** [comment]
I would actually drop the singular ``msg.tag``. Now a user can set a singular tag containing commas but when meta is read, they will multiple tags.
This isn't going to crash anything, it can only lead to unexpected behaviour.
Passing "tag1,tag2, tag3, tag4" as ``msg.tag``could lead to tag3 and tag4 having leading space and not matching.

**Comment by OgelGames** [comment]
Each tag gets commas and whitespace removed here: https://github.com/mt-mods/pipeworks/blob/ce263da6d51f143e98aaf09f849956e69cec3a8e/item_transport.lua#L17

So passing "tag1,tag2, tag3, tag4" as `msg.tag` will result in one tag "tag1tag2tag3tag4", and passing it as `msg.tags` will result it each tag being separated.

> unexpected behaviour

Just need to update the documentation :)
