### ISSUE TITLE
Error when toggling pipeworks_enable_item_tags

### ISSUE THREAD

**Issue by FeXoR-o-Illuria** [mt-mods/pipeworks#117]
Setting `pipeworks_enable_item_tags = false` in a game that already contains injectors with tags set this error occurs in Minetest 5.8:
`AsyncErr: Lua: Runtime error from mod '??' in callback environment_Step(): /home/fexor/.minetest/mods/pipeworks/filter-injector.lua:140: attempt to call field 'sanitize_tags' (a nil value)
stack traceback:
	/home/fexor/.minetest/mods/pipeworks/filter-injector.lua:140: in function 'punch_filter'
	/home/fexor/.minetest/mods/pipeworks/filter-injector.lua:516: in function 'action_on'
	/home/fexor/.minetest/mods/mesecons/mesecons/internal.lua:184: in function </home/fexor/.minetest/mods/mesecons/mesecons/internal.lua:177>
	...e/fexor/.minetest/mods/mesecons/mesecons/actionqueue.lua:137: in function 'execute'
	...e/fexor/.minetest/mods/mesecons/mesecons/actionqueue.lua:111: in function <...e/fexor/.minetest/mods/mesecons/mesecons/actionqueue.lua:73>
	/usr/share/minetest/builtin/common/register.lua:26: in function </usr/share/minetest/builtin/common/register.lua:12>`

**Comment by FeXoR-o-Illuria** [comment]
With this fix I can at least enter the game, yes.

What remains is:
1) Tag tube becomes an unknown node throwing:
2024-03-23 11:44:44: ERROR[Server]: Item "pipeworks:tag_tube_111011" not defined at position (-4,15,64)
The game keeps working ofc. and I guess that's normal?

2) At first enter of the formspec of an injector the tag selection widget is still shown - only after reopening it it seems to have been removed.

So in general it works and I'm probably just nitpicking :D

**Comment by SwissalpS** [comment]
yeah, 1 and 2 are expected to happen in a world that has some previous function deactivated. I don't consider that worth writing an LBM and make things more complicated than needed.

Many thanks for testing and commenting :D
