### ISSUE TITLE
chest dupe

### ISSUE THREAD

**Issue by Kimapr** [mt-mods/pipeworks#118]
see https://github.com/minetest/minetest_game/issues/3103

**Comment by SwissalpS** [comment]
I have a node-detector set to 'default:chest_open' connected to a node-breaker and I can't replicate this on pandorabox.

When there is a node above the chest, node-breaker doesn't even get triggered.
With air above chest node-breaker makes digging sound but doesn't dig anything.

**Comment by Kimapr** [comment]
> I have a node-detector set to 'default:chest_open' connected to a node-breaker and I can't replicate this on pandorabox.
> 
> When there is a node above the chest, node-breaker doesn't even get triggered. With air above chest node-breaker makes digging sound but doesn't dig anything.
> 
> Edit: the chest is of course empty

You can't dig a `default:chest_open`, only the closed variant, putting a node on top of it makes it stay a regular closed chest (but still does an unnecessary node replace after you close the formspec)
obviously the node breaker won't trigger on `default:chest_open` if you don't have a `default:chest_open`

**Comment by Kimapr** [comment]
successfully reproduced this on pandorabox btw
![image](https://github.com/mt-mods/pipeworks/assets/50977029/881dcab6-0f29-4ed5-8c27-62e3c29176d9)
put chest in front of breaker, click button, then open chest before it gets broken; close it after it gets broken
