### ISSUE TITLE
Deployer Farming Issues

### ISSUE THREAD

**Issue by VorTechnix** [mt-mods/pipeworks#12]
Deployer won't plant seeds (although it will plant saplings) and it won't apply bonemeal (and the dispenser just spits the bonemeal item out like any other item).

**Comment by S-S-X** [comment]
Deployer must be pointed towards soil when planting seeds, setup is different from saplings.
Dispenser is not meant to apply bonemeal, use node breaker instead.

Post clear screenshot of your setup if it still does not work after making these changes.

**Comment by VorTechnix** [comment]
Bonemeal in node breaker worked perfectly (that should probably be in the documentation somewhere).

The deployer upside down thing didn't work (I have cotton seeds in it):
![image](https://user-images.githubusercontent.com/45538536/153774108-49eaef09-df25-4176-b0af-d2dd2b0b9e18.png)

Also I'm in a creative world. How do you pipe bonemeal into a nodebreaker in a non creative world?

**Comment by S-S-X** [comment]
Deployer must be touching soil, pointed directly to soil without gap in between. Either from below pointing upwards or from side but not above

**Comment by S-S-X** [comment]
Sorry but it might actually only work from below pointing upwards, possibly I did remember wrong and it wont work sideways.
Try it with soil on top of deployer and deployer pointing upwards.

Also one good way to learn multiple different setups would be to visit some server where automation is used a lot, there's many ways to do these things and actually too many for complete documentation.
These questions you asked however should be documented somehow, at least telling that breaker punches and deployer places (as in left click and right click player actions for any given item).

**Comment by VorTechnix** [comment]
Under the dirt block works fine... annoying to implement though since it can only take a pipe from the back which is the bottom when it's orientated like that.

**Comment by SwissalpS** [comment]
> Bonemeal in node breaker worked perfectly (that should probably be in the documentation somewhere)

The names of the machines already document it. The deployer places nodes while the node breaker breaks them.
So one does the **use** action (dig/lmb) the other the **place** action (rmb).

To plant seeds point deployer from the bottom. To mulch plants/saplings breaker from the side works fine. To grow flowers/grass, point breaker from the side or bottom.

> Under the dirt block works fine... annoying to implement though since it can only take a pipe from the back which is the bottom when it's orientated like that.

Deployers can receive items from tubes from the sides, the tubes just don't attach visually.

Have fun MineTESTING :D

**Comment by VorTechnix** [comment]
Ahh. Great clarification. Thank you!
