### ISSUE TITLE
chest override code is behind minetest_game

### ISSUE THREAD

**Issue by fluxionary** [mt-mods/pipeworks#122]
e.g. https://github.com/minetest/minetest_game/pull/3046

i'm not sure whether someone should just copy all the relevant stuff into https://github.com/mt-mods/pipeworks/blob/master/compat-chests.lua, or if the integration should be done in a better way.

**Comment by fluxionary** [comment]
wait it seems like it's already in there, someone told me it wasn't. never mind

**Comment by S-S-X** [comment]
* Yeah, just few weeks ago 😄 #119
