### ISSUE TITLE
Vacuum tubes dupe

### ISSUE THREAD

**Issue by Ocraw** [mt-mods/pipeworks#130]
When a player picks up items in range of the vacuum tubes there's a chance that also the tubes will pick it up.

Fixed like this:

```lua
local function vacuum(pos, radius)
	radius = radius + 0.5
	local min_pos = vector.subtract(pos, radius)
	local max_pos = vector.add(pos, radius)
	local count = 0
	for _, obj in pairs(minetest.get_objects_in_area(min_pos, max_pos)) do
		local entity = obj:get_luaentity()
		if entity and entity.name == "__builtin:item" then
			if entity.itemstring ~= "" and not entity._removed then
				pipeworks.tube_inject_item(pos, pos, vector.new(0, 0, 0), entity.itemstring)
				entity.itemstring = ""
				count = count + 1
			end
			obj:remove()
			if enable_max and count >= max_items then
				return  -- Don't break tube by vacuuming too many items
			end
		end
	end
end
```

Tested on mineclonia.

**Comment by Ocraw** [comment]
Also, should't it be something like this?

```
local function vacuum(pos, radius)
	radius = radius + 0.5
	local min_pos = vector.subtract(pos, radius)
	local max_pos = vector.add(pos, radius)
	local count = 0
	for _, obj in pairs(minetest.get_objects_in_area(min_pos, max_pos)) do
            local entity = obj:get_luaentity()
            if entity and not entity._removed
            and entity.name == "__builtin:item"
            and entity.itemstring ~= "" then
              if enable_max and count >= max_items then
		    return  -- Don't break tube by vacuuming too many items
              end
              pipeworks.tube_inject_item(pos, pos, vector.new(0, 0, 0), entity.itemstring)
              entity.itemstring = ""
	      count = count + 1
              obj:remove()
            end
         end
end
```

The idea is that we should't delete the item after the first two conditions pass, should be deleted iif the tube actually takes the item.
Not sure about that check for not breaking the tube if enable_max, but seems it has to be checked before the tube can grab more items.

I might be totally off-road here, hope it helps anyway.
Sorry for poor formatting.

**Comment by Ocraw** [comment]
Unless it's designed like that with the goal of clearing clogged farms, preventing tons of entities to hang in one place, but I don't see  how. Which might be a useful settable option, if pipe is full keep erasing items anyway.

**Comment by SwissalpS** [comment]
items not picked up in this step will get processed in next step unless they time-out first.

**Comment by OgelGames** [comment]
Where is `entity._removed` set? I can't find any code that sets it.

**Comment by Ocraw** [comment]
No idea about that sorry, I just snooped at mineclonia hoppers. Sounds like an internal property that marks the entity for deletion, but I'm really just guessing.

**Comment by Ocraw** [comment]
It seems mineclonia uses it to work around object:remove() delay.
https://codeberg.org/mineclonia/mineclonia/src/commit/d3a0525d671a6b7cf97987a3e10cd084db65e85a/mods/ENTITIES/mcl_item_entity/init.lua#L391

https://codeberg.org/mineclonia/mineclonia/src/commit/d3a0525d671a6b7cf97987a3e10cd084db65e85a/mods/ENTITIES/mcl_item_entity/init.lua#L618

Without mineclonia it should be nil and not interfere with anything else (that doesn't set that property for some arcane reasons)

**Comment by OgelGames** [comment]
This is a bug with mineclonia and mineclone, the builtin item entity clears its itemstring when it's picked up, preventing this bug.

That said, it would be a good idea for the vacuum tubes to clear the itemstring when picking up an item, as that would also prevent the bug in mineclonia/mineclone.

**Comment by Ocraw** [comment]
Would appreciate if you could elaborate on that, where should it clear the itemstring?
Either way thanks for looking into it and for the infos.

**Comment by OgelGames** [comment]
I've created PRs for both:
https://codeberg.org/mineclonia/mineclonia/pulls/1665
https://git.minetest.land/VoxeLibre/VoxeLibre/pulls/4530

**Comment by corarona** [comment]
Iirc the _removed property was put in to prevent a very similar kind of dupe with hoppers, however removing the itemstring seems like a good idea either way.
