### ISSUE TITLE
Nodebreaker: bucket full of water stuck in.

### ISSUE THREAD

**Issue by mazes-80** [mt-mods/pipeworks#137]
Bucket full of water will be stuck in node breakers after using last empty one from a stack.
It breaks automations some automation I set up when it used to work.

**Comment by mazes-80** [comment]
Wow blowing fast fix, it works now.
But I do not get how splitting the line fixed the thing, surely a little detail I do not see.
I would be interested in understanding why unique line did not drop the item, already checked before opening the bug, and did not see why it did not work.

**Comment by OgelGames** [comment]
Because the `stack` variable need to be updated with the new itemstack returned from `on_use`, so that it can be compared to the `old_stack` correctly. In this case, when the last bucket gets used, the itemstack changes from an empty bucket to a water bucket.
