### ISSUE TITLE
Vertical digiline tubes no longer work as they did

### ISSUE THREAD

**Issue by SwissalpS** [mt-mods/pipeworks#145]
See: https://github.com/pandorabox-io/in-game/issues/401
The server didn't change any settings and existing builds are affected by recent vertical signal handling being changed.

**Comment by MCLV-pandorabox** [comment]
Ah. most unfortunate. I hope this will be solved soon. This would explain why some of my builds could have failed too.

**Comment by SwissalpS** [comment]
Looks like it is because the new feature was made opt-out instead of opt-in.
