### ISSUE TITLE
Reject after filling inventory with stack splitting

### ISSUE THREAD

**Issue by S-S-X** [mt-mods/pipeworks#19]
Marked as a question because I'm not really sure if this should be handled here or in mods (which is possible already but complicates things a lot).

When feeding large stacks using tubes to inventories with stack splitting enabled it can (and most often will) cause stacks to get stuck between inventory and tube.

This seems to happen because it seems like inventory with stack splitting enabled will always accept stack but if inventory is actually full then it returns stack to originating tube.
Then inventories have higher priority and this can cause stack to be sent again back towards inventory which is full but accepts stacks because stack splitting is enabled.

Solving this without looking at inventory contents would be possible with stack splitting rate limiters, this can however cause missed stacks in some special cases.
Solving this by checking if returned stack was not splitted and in that case disallowing return or if other direction is not possible then dropping stack to ground would be more accurate option.

I've not tested much what actually affects this behavior but it seems that sending a lot of stacks will make some stacks bypass inventory.
Also not sure if this is actually issue only with some specific tube types but if it is then sorting tube would probably be good for testing.

**Comment by OgelGames** [comment]
This *should* be handled by the `can_insert` function of a pipeworks-compatible node, if it returns the correct value. (something I fixed recently with drawer controllers: https://github.com/minetest-mods/drawers/pull/68)

The default if `can_insert` is not defined is to insert the stack:
https://github.com/mt-mods/pipeworks/blob/5aa0501872c618171dc58ade1d75f0db989f3bd4/item_transport.lua#L111-L112

I'd say it should be fixed in the node definition, pipeworks already does what it should.

**Comment by SwissalpS** [comment]
> I'd say it should be fixed in the node definition, pipeworks already does what it should.

So we can close this? Or do we need it as reminder to check other mods and update them?

**Comment by S-S-X** [comment]
> So we can close this? Or do we need it as reminder to check other mods and update them?

Should prob add issue to Technic repo and then close this one.

**Comment by S-S-X** [comment]
Closing this, can continue with implementation / discussion about technical details on linked issue mt-mods/technic#310
