### ISSUE TITLE
pipeworks reverts furnace fixes in minetest_game

### ISSUE THREAD

**Issue by fluxionary** [mt-mods/pipeworks#20]
e.g. they don't make the nice new sounds, and fuel isn't consumed when they are unloaded while they are processing.

**Comment by wsor4035** [comment]
probably because it is a copy paste and edit job from the furnace code a long time ago, rather than an override what is needed job. for refence https://github.com/mt-mods/pipeworks/blob/master/compat-furnaces.lua
