### ISSUE TITLE
Item group support for autocrafter

### ISSUE THREAD

**Issue by S-S-X** [mt-mods/pipeworks#3]
Autocrafter has troubles using item groups in input recipes, make it better.
I think Rubenwardy had PR open for this on GitLab, no idea if there's something useful or not but might be.

**Comment by wsor4035** [comment]
@rubenwardy ping

**Comment by rubenwardy** [comment]
My PR is blocked waiting on an engine PR. If only we knew some engine devs

**Comment by Gustavo6046** [comment]
> My PR is blocked waiting on an engine change. If only we knew some engine devs

Are you referring to 5.5.0 @rubenwardy ? In that case, pingpingping!
