### ISSUE TITLE
Node breakers no longer accept buckets

### ISSUE THREAD

**Issue by GrimPixel** [mt-mods/pipeworks#35]
It simply doesn't work.

It is working in singleplayer. Maybe it is specific to some servers.

**Comment by BuckarooBanzay** [comment]
> It is working in singleplayer. Maybe it is specific to some servers.

Is there a way you can reproduce the issue? Not sure if your bug-report helps if it isn't :/

And: do i get this right: this happened on a public server?

**Comment by GrimPixel** [comment]
They say it's a bug on that server. I guess everything is fine. Thank you.

**Comment by SwissalpS** [comment]
make sure to update to current version. Then dig and place again any nodebreakers that didn't work.
There was a commit that had node breakers nerfed.
