### ISSUE TITLE
[Question] Multiple Inputs to a single node?

### ISSUE THREAD

**Issue by sirrobzeroone** [mt-mods/pipeworks#38]
I don't think this is a possible but thought it best to ask.

Scenario
I have a configured node which has two source inventories for ingredients "src_1" and "src_2". 

I can see in pipeworks that I can configure a single input by doing the below inside node_def.pipe - code might be a bit off but something like:
```
		can_insert = function(pos,node,stack,direction, owner)

			local meta = minetest.get_meta(pos)
			local inv = meta:get_inventory()

			return inv:room_for_item("src_1", stack)
		end,
```
So that will insert pipe items into src_1

Back to my question can a pipe carry multiple item types? and if yes is there a builtin sub setting or will I need to manually sort them - I don't mind manually sorting but just not sure if the pipe can even carry 2 types of items or how pipeworks will select what stack to grab next? Happy if there's a receiving node/machine that someone can point me to and I'll just study the code. I'm trying to avoid having to read all the pipeworks code and/or write some test code and see what does and doesn't work. 

Thanks for any help

**Comment by S-S-X** [comment]
Differnet sides as inputs for different inventory lists, example as implemented in Technic mod: https://github.com/mt-mods/technic/blob/b4cde134128091bb71e3d056f51814f64bfa79cb/technic/machines/register/battery_box.lua#L78-L106

**Comment by SwissalpS** [comment]
alloy furnace in technic mod is also an example of multiple input inventories

**Comment by sirrobzeroone** [comment]
Cheers both, much appreciate the info and fast response.
