### ISSUE TITLE
Autocraft cannot be opened

### ISSUE THREAD

**Issue by IFRFSX** [mt-mods/pipeworks#4]
The switch cannot be turned on，Even if the formula is correct。

**Comment by IFRFSX** [comment]
Older version on the content site

**Comment by S-S-X** [comment]
> The switch cannot be turned on，Even if the formula is correct。
> The older version on the content website does not have this problem。

Does this happen with current ContentDB release or latest from git master branch?

Asking because I remember there was issue like this some time ago and it was fixed but possibly ContentDB release is already too old and still has this problem.

**Comment by IFRFSX** [comment]
#5 
This is my patch.

**Comment by S-S-X** [comment]
Seems like it is problem when optional dependency digilines is not installed?
ContentDB is at db6d1bd and I think this was probably fixed on 7ba68534
