### ISSUE TITLE
Change 'mesecons' from optional dependencies to dependencies

### ISSUE THREAD

**Issue by GrimPixel** [mt-mods/pipeworks#44]
If I don't enable mesecons, it will say

ModError: Failed to load and run script from /home/user/.minetest/mods/pipeworks/init.lua:
/home/user/.minetest/mods/pipeworks/lua_tube.lua:302: attempt to index global 'mesecon' (a nil value)
stack traceback:
	/home/user/.minetest/mods/pipeworks/lua_tube.lua:302: in main chunk
	[C]: in function 'dofile'
	/home/user/.minetest/mods/pipeworks/init.lua:147: in main chunk
Check debug.txt for details.

**Comment by BuckarooBanzay** [comment]
Can you check your setup: this should not happen unless you have the `digilines` mod enabled (which should not work without mesecons iirc)

https://github.com/mt-mods/pipeworks/blob/e45eca76e16ee68a0454799b8035aa2233cb72de/init.lua#L181-L184

Your mod(s) might be out of date

**Comment by S-S-X** [comment]
I think lua tube requires both so we could make it explicit and not depend on external dependency
```diff
- 		(minetest.get_modpath("mesecons") or minetest.get_modpath("digilines")) then
+ 		minetest.get_modpath("mesecons") and minetest.get_modpath("digilines") then
```

**Comment by wsor4035** [comment]
> I think lua tube requires both so we could make it explicit to not depend on external dependency
> 
> ```diff
> - 		(minetest.get_modpath("mesecons") or minetest.get_modpath("digilines")) then
> + 		minetest.get_modpath("mesecons") and minetest.get_modpath("digilines") then
> ```
> 
> or if digilines is actually optional for lua tube (mesecons isn't, probably same with digilines but not 100% sure):
> 
> ```diff
> - if pipeworks.enable_lua_tube and 
> - 		(minetest.get_modpath("mesecons") or minetest.get_modpath("digilines")) then 
> + if pipeworks.enable_lua_tube and minetest.get_modpath("mesecons") then
> ```

your second option should be `if pipeworks.enable_lua_tube and pipeworks.enable_lua_tube and minetest.get_modpath("mesecons") then`

**Comment by wsor4035** [comment]
> Can you check your setup: this should not happen unless you have the `digilines` mod enabled (which should not work without mesecons iirc)
> 
> https://github.com/mt-mods/pipeworks/blob/e45eca76e16ee68a0454799b8035aa2233cb72de/init.lua#L181-L184
> 
> Your mod(s) might be out of date

it does "work" without mesecons ~~or at least it boots without crashing~~ https://github.com/minetest-mods/digilines/blob/master/mod.conf#L2

**Comment by BuckarooBanzay** [comment]
> it does "work" without mesecons

Sooo, this is still an issue then? see first post :wink:
