### ISSUE TITLE
Mineclone support into chests and furnace compat files

### ISSUE THREAD

**Issue by wsor4035** [mt-mods/pipeworks#52]
posting since `MatthiasZM` requested support for this. currently only mtg and hades are supported.

side notes:
* looking at stuff like https://github.com/mt-mods/pipeworks/blob/master/compat-chests.lua#L45 (correct me if im wrong @sfence) need to be tweaked for just hades.
* might be best to make a hash table that makes stuff for each game to reduce duplication and if/else if spam

**Comment by nonfreegithub** [comment]
copiying and pasting from #58

I suggest include "mineclone" in this issue title

> pipeworks work fine in mineclone, but it does not interact with mineclone chests
> 
> it can override mineclone chests to compat with
> 
> or maybe with mineclone barrels...

**Comment by nonfreegithub** [comment]
> > or maybe with mineclone barrels...

https://github.com/mt-mods/pipeworks/pull/81

**Comment by wsor4035** [comment]
should be resolved by https://github.com/mt-mods/pipeworks/pull/81
