### ISSUE TITLE
Tubes break up despite standard mod configuration

### ISSUE THREAD

**Issue by chrbinder** [mt-mods/pipeworks#7]
I encountered some broken tubes (broken_tube_4, broken_tube_3 and broken_tube_6) despite not having set `pipeworks_enable_items_per_tube_limit` in minetest.conf. I set `pipeworks_enable_items_per_tube_limit` to false, but even that didn't help.

Is it possible that tubes break even though they should not?

**Comment by OgelGames** [comment]
Yep, it's due to a small mistake in the code:
https://github.com/mt-mods/pipeworks/blob/794cae675e3e065077239e0e14391067a8c48ae6/item_transport.lua#L2
`minetest.settings:get()` returns either `nil` or a string, and Lua interprets the string `"false"` as true.

**Comment by OgelGames** [comment]
Note that the default is still enabled, but you should be able to disable it now.
