### ISSUE TITLE
Avoiding suggestions already on the TODO list

### ISSUE THREAD

**Issue by The4codeblocks** [mt-mods/pipeworks#75]
There doesn't appear to be any guidelines in creating issues, that can lead to certain users to suggest suggestions already on the TODO list.

I suggest adding guidelines for suggestion, with reading the TODO list being one of them.

**Comment by wsor4035** [comment]
last i checked, we dont even have a todo list. if your referring to checking open issues, that should be common sense

**Comment by S-S-X** [comment]
We do have TODO list, it is publicly accessible through this link: https://github.com/mt-mods/pipeworks/issues 😆

Anyway, just saying that we do not really need separate lists, PRs and issues are enough for project like this (ppl do start assigning issues when there's more traffic or as a reminder, rarely needed anyway) and next logical step would anyway be milestones.

**Comment by OgelGames** [comment]
I assume OP is referring to this: https://github.com/mt-mods/pipeworks/blob/master/todo/pressure_logic.txt

**Comment by The4codeblocks** [comment]
> Maybe OP is referring to this? https://github.com/mt-mods/pipeworks/blob/master/todo/pressure_logic.txt

Yes, I did.
