### ISSUE TITLE
Request: Add support for Industrial Furnaces mod

### ISSUE THREAD

**Issue by AmyMoriyama** [mt-mods/pipeworks#8]
Would be real nice to be able to use industrial furnaces with pipeworks.

https://github.com/PetiAPocok/minetest_extended/tree/master/mods/industrial_furnace

**Comment by wsor4035** [comment]
it is the job of that mod to add support to work with the pipeworks api.

**Comment by BuckarooBanzay** [comment]
A few examples on how this can be achieved:
* `vacuum` mod, airpump with tube-support: https://github.com/mt-mods/vacuum/blob/a75119f8488d6f7fda08e9b8fad211b0db220d82/airpump.lua#L162-L176
* `atm` mod with an atm that supports collecting money from a tube: https://github.com/6r1d/atm/blob/6a9958659e68cda61e3ca8023241c0103f9cbeb8/nodes.lua#L14-L68
* And of course most machines in the `technic` mod: https://github.com/mt-mods/technic
