### ISSUE TITLE
Teleport tube: replace deprecated inline metadata values ...

### ISSUE THREAD

**Issue by SmallJoker** [mt-mods/pipeworks#93]
using a dedicated formspec builder function

This also properly escapes the `S` translation.

I noticed that this mod is not in minetest-mods, thus here's my patch as a file instead of me pushing it right to the repo:

[0001-Teleport-tube-replace-deprecated-inline-metadata-val.patch.txt](https://github.com/mt-mods/pipeworks/files/13367813/0001-Teleport-tube-replace-deprecated-inline-metadata-val.patch.txt)

**Comment by BuckarooBanzay** [comment]
> I noticed that this mod is not in minetest-mods, thus here's my patch as a file instead of me pushing it right to the repo:

could you elaborate how we would improve the situation?

**Comment by SmallJoker** [comment]
@BuckarooBanzay Not at all at the moment. It was a self talk to justify dropping the patch file in there instead of forking the project and changing my clone's git config.

**Comment by S-S-X** [comment]
5.7 docs says that

> Usage of the `${k}` syntax in formspecs is not deprecated.

Will it be deprecated in next version or something?

**Comment by SmallJoker** [comment]
@S-S-X Good catch. What a blunder from my side. You're right. I totally missed the second half of the paragraph.

Here's the original fix about the misplaced escape character. My first commit solves that too, but it did too many unnecessary changes. Feel free to pick whatever you prefer.

[0001-Teleport-tube-Move-formspec-escape-outside-of-transl.patch.txt](https://github.com/mt-mods/pipeworks/files/13369671/0001-Teleport-tube-Move-formspec-escape-outside-of-transl.patch.txt)
